run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - migrations
    - documentation

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - gocritic
    - gosec
    - misspell
    - revive
    - unconvert
    - unparam
    - whitespace

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: data-storage
  revive:
    rules:
      - name: exported
        severity: warning
      - name: unexported-return
        severity: warning
      - name: error-return
        severity: warning
      - name: if-return
        severity: warning
      - name: increment-decrement
        severity: warning
      - name: var-naming
        severity: warning
      - name: range
        severity: warning
      - name: receiver-naming
        severity: warning
      - name: unexported-naming
        severity: warning
      - name: var-declaration
        severity: warning
      - name: range-val-in-closure
        severity: warning
      - name: range-val-address
        severity: warning
      - name: waitgroup-by-value
        severity: warning
      - name: atomic
        severity: warning
      - name: empty-lines
        severity: warning
      - name: line-length-limit
        severity: warning
        arguments:
          - "120"
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gosec:
    severity: medium
    confidence: medium

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0

